---
network:
  # Worker IPs are simply incremented from the uptrace IP.
  uptrace_ip: 10.10.0.2
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
nodes:
  uptrace:
    cpu: 1
    memory: 3072
# Mount additional shared folders from the host into each virtual machine.
# Note that the project directory is automatically mounted at /vagrant.
# shared_folders:
#   - host_path: ../images
#     vm_path: /vagrant/images
software:
  box: generic/debian11